name: CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Set up Java
        uses: actions/setup-java@v1.0.0

        with:
          version: 1.11

      - name: Set up Gradle properties
        run: |
          mkdir -p ~/.gradle
          echo "githubToken=${{ secrets.GITHUB_TOKEN }}" >> ~/.gradle/gradle.properties

      - name: Gradle (Build)
        run: sh gradlew build

      - name: Gradle (Publish)
        run: sh gradlew -Pkotdis.user=${{ secrets.MAVEN_USER }} -Pkotdis.password=${{ secrets.MAVEN_PASSWORD }} publish

      - name: Rename Artifacts
        run: |
          mkdir build/artifacts

          cp build/libs/* build/artifacts
          mv build/artifacts/*-all.jar build/artifacts/database.jar
          mv build/artifacts/*-*.*.jar build/artifacts/database-slim.jar

      - name: Upload artifact (Slim JAR)
        uses: actions/upload-artifact@v1.0.0

        with:
          name: Slim JAR
          path: build/artifacts/database-slim.jar

      - name: Upload artifact (Production JAR)
        uses: actions/upload-artifact@v1.0.0

        with:
          name: Production JAR
          path: build/artifacts/database.jar
